import type { Wheel } from "../types/wheel.types";

export const wheels: Wheel[] = [
  {
    id: "1",
    name: "Main Wheel",
    description: "Daily spin rewards",
    status: "active",
    spinCost: 10,
    maxSpinsPerUser: 5,
    backgroundColor: "#ffffff",
    borderColor: "#000000",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    segments: [
      {
        id: "1",
        label: "10 Coins",
        color: "#FF5733",
        weight: 20,
        prizeType: "coins",
        prizeAmount: 10,
        imageUrl: "",
      },
      {
        id: "2",
        label: "Nothing",
        color: "#cccccc",
        weight: 30,
        prizeType: "nothing",
        prizeAmount: 0,
        imageUrl: "",
      },
      {
        id: "3",
        label: "Free Spin",
        color: "#33FF57",
        weight: 50,
        prizeType: "freeSpin",
        prizeAmount: 1,
        imageUrl: "",
      },
    ],
  },
  {
    id: "2",
    name: "Premium Wheel",
    description: "High-value rewards for premium users",
    status: "active",
    spinCost: 50,
    maxSpinsPerUser: 3,
    backgroundColor: "#f8f9fa",
    borderColor: "#ffd700",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    segments: [
      {
        id: "1",
        label: "100 Coins",
        color: "#FFD700",
        weight: 10,
        prizeType: "coins",
        prizeAmount: 100,
        imageUrl: "",
      },
      {
        id: "2",
        label: "50 Coins",
        color: "#FFA500",
        weight: 20,
        prizeType: "coins",
        prizeAmount: 50,
        imageUrl: "",
      },
      {
        id: "3",
        label: "Free Spin",
        color: "#00C853",
        weight: 30,
        prizeType: "freeSpin",
        prizeAmount: 1,
        imageUrl: "",
      },
      {
        id: "4",
        label: "Jackpot",
        color: "#FF1744",
        weight: 5,
        prizeType: "coins",
        prizeAmount: 500,
        imageUrl: "",
      },
      {
        id: "5",
        label: "Try Again",
        color: "#9E9E9E",
        weight: 35,
        prizeType: "nothing",
        prizeAmount: 0,
        imageUrl: "",
      },
    ],
  },
  {
    id: "3",
    name: "Holiday Wheel",
    description: "Special holiday rewards",
    status: "inactive",
    spinCost: 0,
    maxSpinsPerUser: 1,
    backgroundColor: "#fff3e0",
    borderColor: "#ff9800",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    segments: [
      {
        id: "1",
        label: "Gift Box",
        color: "#8E24AA",
        weight: 40,
        prizeType: "bonus",
        prizeAmount: 1,
        imageUrl: "",
      },
      {
        id: "2",
        label: "Free Spin",
        color: "#43A047",
        weight: 30,
        prizeType: "freeSpin",
        prizeAmount: 1,
        imageUrl: "",
      },
      {
        id: "3",
        label: "100 Coins",
        color: "#FB8C00",
        weight: 20,
        prizeType: "coins",
        prizeAmount: 100,
        imageUrl: "",
      },
      {
        id: "4",
        label: "Nothing",
        color: "#BDBDBD",
        weight: 10,
        prizeType: "nothing",
        prizeAmount: 0,
        imageUrl: "",
      },
    ],
  },
  {
    id: "4",
    name: "New User Wheel",
    description: "Welcome bonus for new users",
    status: "active",
    spinCost: 0,
    maxSpinsPerUser: 1,
    backgroundColor: "#e3f2fd",
    borderColor: "#2196f3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    segments: [
      {
        id: "1",
        label: "20 Coins",
        color: "#2196F3",
        weight: 50,
        prizeType: "coins",
        prizeAmount: 20,
        imageUrl: "",
      },
      {
        id: "2",
        label: "Free Spin",
        color: "#4CAF50",
        weight: 30,
        prizeType: "freeSpin",
        prizeAmount: 1,
        imageUrl: "",
      },
      {
        id: "3",
        label: "Bonus Pack",
        color: "#9C27B0",
        weight: 20,
        prizeType: "bonus",
        prizeAmount: 1,
        imageUrl: "",
      },
    ],
  },
  {
    id: "5",
    name: "Risk Wheel",
    description: "High risk, high reward",
    status: "draft",
    spinCost: 25,
    maxSpinsPerUser: 2,
    backgroundColor: "#212121",
    borderColor: "#ff5252",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    segments: [
      {
        id: "1",
        label: "Big Win",
        color: "#00E676",
        weight: 5,
        prizeType: "coins",
        prizeAmount: 1000,
        imageUrl: "",
      },
      {
        id: "2",
        label: "Medium Win",
        color: "#FFEA00",
        weight: 15,
        prizeType: "coins",
        prizeAmount: 200,
        imageUrl: "",
      },
      {
        id: "3",
        label: "Small Win",
        color: "#FF9100",
        weight: 30,
        prizeType: "coins",
        prizeAmount: 50,
        imageUrl: "",
      },
      {
        id: "4",
        label: "Lose",
        color: "#D50000",
        weight: 50,
        prizeType: "nothing",
        prizeAmount: 0,
        imageUrl: "",
      },
    ],
  },
];
